/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Day {
  'exercises' : Array<Exercise>,
  'week' : bigint,
  'dayNumber' : bigint,
  'dayType' : DayType,
}
export type DayType = { 'rest' : null } |
  { 'workout' : null } |
  { 'recovery' : null };
export interface DietPlan {
  'foodOptions' : Array<FoodItem>,
  'dailyCalorieTarget' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Exercise {
  'name' : string,
  'reps' : bigint,
  'restSec' : bigint,
  'animationUrl' : string,
  'durationSec' : bigint,
}
export type FitnessGoal = { 'improveFitness' : null } |
  { 'buildMuscle' : null } |
  { 'generalHealth' : null } |
  { 'loseWeight' : null };
export interface FoodItem { 'calories' : bigint, 'name' : string }
export interface MealLog {
  'date' : string,
  'totalCalories' : bigint,
  'items' : Array<FoodItem>,
}
export interface Program { 'days' : Array<Day> }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type StartingLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface SubscriptionStatus {
  'startTime' : Timestamp,
  'active' : boolean,
  'endTime' : Timestamp,
  'daysRemaining' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfileView {
  'id' : UserId,
  'fitnessGoal' : FitnessGoal,
  'name' : string,
  'onboardingComplete' : boolean,
  'startingLevel' : StartingLevel,
}
export interface UserProgressView {
  'completedDays' : Array<bigint>,
  'streak' : bigint,
  'completionPercentage' : bigint,
  'dailyCalorieTarget' : bigint,
  'mealLogs' : Array<MealLog>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'activateSubscription' : ActorMethod<[], SubscriptionStatus>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOnboarding' : ActorMethod<
    [string, FitnessGoal, StartingLevel],
    UserProfileView
  >,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCalorieLog' : ActorMethod<[string], [] | [MealLog]>,
  'getDay' : ActorMethod<[bigint], [] | [Day]>,
  'getDaysByWeek' : ActorMethod<[bigint], Array<Day>>,
  'getDietPlan' : ActorMethod<[], DietPlan>,
  'getProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getProgram' : ActorMethod<[], Program>,
  'getProgress' : ActorMethod<[], UserProgressView>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDayUnlocked' : ActorMethod<[bigint], boolean>,
  'logMeal' : ActorMethod<[string, Array<FoodItem>], MealLog>,
  'markDayComplete' : ActorMethod<[bigint], boolean>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];