/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Timestamp = IDL.Int;
export const SubscriptionStatus = IDL.Record({
  'startTime' : Timestamp,
  'active' : IDL.Bool,
  'endTime' : Timestamp,
  'daysRemaining' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FitnessGoal = IDL.Variant({
  'improveFitness' : IDL.Null,
  'buildMuscle' : IDL.Null,
  'generalHealth' : IDL.Null,
  'loseWeight' : IDL.Null,
});
export const StartingLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const UserId = IDL.Principal;
export const UserProfileView = IDL.Record({
  'id' : UserId,
  'fitnessGoal' : FitnessGoal,
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'startingLevel' : StartingLevel,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FoodItem = IDL.Record({ 'calories' : IDL.Nat, 'name' : IDL.Text });
export const MealLog = IDL.Record({
  'date' : IDL.Text,
  'totalCalories' : IDL.Nat,
  'items' : IDL.Vec(FoodItem),
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'restSec' : IDL.Nat,
  'animationUrl' : IDL.Text,
  'durationSec' : IDL.Nat,
});
export const DayType = IDL.Variant({
  'rest' : IDL.Null,
  'workout' : IDL.Null,
  'recovery' : IDL.Null,
});
export const Day = IDL.Record({
  'exercises' : IDL.Vec(Exercise),
  'week' : IDL.Nat,
  'dayNumber' : IDL.Nat,
  'dayType' : DayType,
});
export const DietPlan = IDL.Record({
  'foodOptions' : IDL.Vec(FoodItem),
  'dailyCalorieTarget' : IDL.Nat,
});
export const Program = IDL.Record({ 'days' : IDL.Vec(Day) });
export const UserProgressView = IDL.Record({
  'completedDays' : IDL.Vec(IDL.Nat),
  'streak' : IDL.Nat,
  'completionPercentage' : IDL.Nat,
  'dailyCalorieTarget' : IDL.Nat,
  'mealLogs' : IDL.Vec(MealLog),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'activateSubscription' : IDL.Func([], [SubscriptionStatus], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOnboarding' : IDL.Func(
      [IDL.Text, FitnessGoal, StartingLevel],
      [UserProfileView],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCalorieLog' : IDL.Func([IDL.Text], [IDL.Opt(MealLog)], ['query']),
  'getDay' : IDL.Func([IDL.Nat], [IDL.Opt(Day)], ['query']),
  'getDaysByWeek' : IDL.Func([IDL.Nat], [IDL.Vec(Day)], ['query']),
  'getDietPlan' : IDL.Func([], [DietPlan], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getProgram' : IDL.Func([], [Program], ['query']),
  'getProgress' : IDL.Func([], [UserProgressView], ['query']),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDayUnlocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'logMeal' : IDL.Func([IDL.Text, IDL.Vec(FoodItem)], [MealLog], []),
  'markDayComplete' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Timestamp = IDL.Int;
  const SubscriptionStatus = IDL.Record({
    'startTime' : Timestamp,
    'active' : IDL.Bool,
    'endTime' : Timestamp,
    'daysRemaining' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FitnessGoal = IDL.Variant({
    'improveFitness' : IDL.Null,
    'buildMuscle' : IDL.Null,
    'generalHealth' : IDL.Null,
    'loseWeight' : IDL.Null,
  });
  const StartingLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const UserProfileView = IDL.Record({
    'id' : UserId,
    'fitnessGoal' : FitnessGoal,
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'startingLevel' : StartingLevel,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FoodItem = IDL.Record({ 'calories' : IDL.Nat, 'name' : IDL.Text });
  const MealLog = IDL.Record({
    'date' : IDL.Text,
    'totalCalories' : IDL.Nat,
    'items' : IDL.Vec(FoodItem),
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'restSec' : IDL.Nat,
    'animationUrl' : IDL.Text,
    'durationSec' : IDL.Nat,
  });
  const DayType = IDL.Variant({
    'rest' : IDL.Null,
    'workout' : IDL.Null,
    'recovery' : IDL.Null,
  });
  const Day = IDL.Record({
    'exercises' : IDL.Vec(Exercise),
    'week' : IDL.Nat,
    'dayNumber' : IDL.Nat,
    'dayType' : DayType,
  });
  const DietPlan = IDL.Record({
    'foodOptions' : IDL.Vec(FoodItem),
    'dailyCalorieTarget' : IDL.Nat,
  });
  const Program = IDL.Record({ 'days' : IDL.Vec(Day) });
  const UserProgressView = IDL.Record({
    'completedDays' : IDL.Vec(IDL.Nat),
    'streak' : IDL.Nat,
    'completionPercentage' : IDL.Nat,
    'dailyCalorieTarget' : IDL.Nat,
    'mealLogs' : IDL.Vec(MealLog),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'activateSubscription' : IDL.Func([], [SubscriptionStatus], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOnboarding' : IDL.Func(
        [IDL.Text, FitnessGoal, StartingLevel],
        [UserProfileView],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCalorieLog' : IDL.Func([IDL.Text], [IDL.Opt(MealLog)], ['query']),
    'getDay' : IDL.Func([IDL.Nat], [IDL.Opt(Day)], ['query']),
    'getDaysByWeek' : IDL.Func([IDL.Nat], [IDL.Vec(Day)], ['query']),
    'getDietPlan' : IDL.Func([], [DietPlan], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
    'getProgram' : IDL.Func([], [Program], ['query']),
    'getProgress' : IDL.Func([], [UserProgressView], ['query']),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDayUnlocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'logMeal' : IDL.Func([IDL.Text, IDL.Vec(FoodItem)], [MealLog], []),
    'markDayComplete' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };